# Generated by Django 4.1 on 2024-05-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloserRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('ranking', models.IntegerField(verbose_name='랭킹')),
                ('closer', models.CharField(max_length=50, verbose_name='클로저')),
                ('closer_name', models.CharField(max_length=50, verbose_name='클로저명')),
                ('level', models.IntegerField(verbose_name='레벨')),
                ('grade', models.CharField(max_length=50, verbose_name='등급')),
                ('character_name', models.CharField(max_length=50, verbose_name='캐릭터명')),
                ('total_combat_power', models.CharField(max_length=50, verbose_name='종합 전투력')),
                ('total_combat_power_int', models.IntegerField(verbose_name='종합 전투력(int)')),
            ],
        ),
    ]
